name: 'Terraform GitHub Actions'
on:
  push:
    branches: 
        - main
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform fmt
        id: fmt
        working-directory: ./terraform 
        run: terraform fmt
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: Terraform Init
        id: init
        working-directory: ./terraform 
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform 
        run: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 