name: 'Terraform GitHub Actions'
on:
  push:
    branches: 
        - main
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

      - name: Terraform Plan
        id: plan
        run: |
         ls -R 
         terraform plan -var-file=terraform.tfvars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 